import 'package:flutter/material.dart';

class MyIcons {
  static const loginIcon = Icons.login_outlined;
  static const visibilityOn = Icons.visibility_outlined;
  static const visibilityOff = Icons.visibility_off_outlined;
  static const mail = Icons.mail_outline_rounded;
  static const password = Icons.password_outlined;
  static const user = Icons.person_outline_outlined;
  static const addPerson = Icons.person_add_alt_1_outlined;
  static const resetPassword = Icons.key_outlined;
  static const add = Icons.add;
  static const search = Icons.search;
  static const filter = Icons.tune_outlined;
  static const lock = Icons.lock_person_rounded;
  static const nextIcon = Icons.arrow_forward_outlined;
  static const nextIOSIcon = Icons.arrow_forward_ios_outlined;
  static const logout = Icons.logout_outlined;
  static const backIOSIcon = Icons.arrow_back_ios_new_outlined;
  static const home = Icons.home_outlined;
  static const listAlt = Icons.list_alt_outlined;
  static const list = Icons.list;
  static const grid = Icons.grid_view_outlined;
  static const profile = Icons.person_2_outlined;
  static const date = Icons.date_range_outlined;
  static const update = Icons.update;
  static const save = Icons.bookmark_add_outlined;
  static const saveIcon = Icons.bookmark;
  static const saved = Icons.bookmark_added_rounded;
  static const delete = Icons.delete_forever;
  static const popupMenu = Icons.more_vert;
  static const editNote = Icons.edit_note;
  static const confirm = Icons.check_outlined;
  static const company = Icons.business_center_outlined;
  static const department = Icons.apartment_outlined;
  static const alert = Icons.info_outline;
  static const drawer = Icons.menu;
  //create advert
  static const position = Icons.badge_outlined;
  static const level = Icons.grade_outlined;
  static const timinig = Icons.access_time_outlined;
  static const skill = Icons.computer_outlined;
  static const wage = Icons.money;
  static const language = Icons.language;
  static const number = Icons.format_list_numbered_outlined;
  static const hobbies = Icons.sports_esports;
  static const smartPhone = Icons.phone_android_outlined;
  static const phone = Icons.phone_outlined;
  static const website = Icons.web_outlined;
  static const edit = Icons.edit_outlined;
  static const location = Icons.location_on_outlined;
  static const camera = Icons.camera_alt_outlined;
  static const image = Icons.image_outlined;
}
